services:
  mdp:
    container_name: mdp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
    environment:
      USERNAME: ${USERNAME}
      SSH_PUBLIC_KEY: ${SSH_PUBLIC_KEY}
    ports:
      - "2222:22"
    volumes:
      - ../code:/home/${USERNAME}/code
      - ssh_keys:/etc/ssh
    restart: unless-stopped

volumes:
  ssh_keys:
